language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7.0
      env: COLLECT_COVERAGE=true
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v